source "https://rubygems.org"

gem "logging"
gem "uuid"
gem "dm-sqlite-adapter"
gem "dm-migrations"
gem "ripl"
gem "pry"
gem "pry-byebug"
gem "typhoeus",           "1.1.2"
gem "diaspora_federation", github: "diaspora/diaspora_federation", branch: "develop"
gem "diaspora_federation-sinatra_app", github: "cmrd-senya/diaspora_federation-sinatra_app"
gem "rack-ssl"
